config/routes.rb
Rails.application.routes.draw do
  resources :string_calculators, only: [:new, :create]
  root 'string_calculators#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/string_calculator.rb
class StringCalculator < ApplicationRecord
  
  def self.add(numbers)
    return 0 if numbers.empty?

    delimiter = ','
    num_list = numbers.split(delimiter)

    result_array = num_list.flat_map do |element|
      element.split('"').flat_map do |part|
        part.split(/\\n|;/)
      end.map(&:to_i)
    end
    handle_negatives(result_array)
    result_array.sum
  end

  def self.handle_negatives(numbers_array)
    negatives = numbers_array.select { |num| num.negative? }
    raise "Negative numbers not allowed: #{negatives.join(',')}" if negatives.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/string_calculators_controller.rb
class StringCalculatorsController < ApplicationController
  def new
    @result = params[:result]
    @error = params[:error]
  end

  def create
    result = StringCalculator.add(calculator_params[:numbers])
    redirect_to new_string_calculator_path(result: result)
  rescue => e
    redirect_to new_string_calculator_path(error: e.message)
  end

  private

  def calculator_params
    params.require(:calculator).permit(:numbers)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/string_calculators_helper.rb
module StringCalculatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncubyteTddAssessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/string_calculators/new.html.erb
<h1>String Calculator</h1>

<%= form_with url: string_calculators_path, method: :post do %>
  <div>
    <%= label_tag :numbers, "Enter numbers:" %>
    <%= text_field_tag 'calculator[numbers]' %>
  </div>
  <div>
    <%= submit_tag "Calculate" %>
  </div>
<% end %>

<% if @result %>
  <p>Result: <%= @result %></p>
<% elsif @error %>
  <p>Error: <%= @error %></p>
<% end %>